### ISSUE TITLE
Convert percent_type_or_auto to JSON Schema

### ISSUE THREAD

**Issue by terry-codecov** [codecov/vscode#32]
The extension is incorrectly validating the target field due to not yet converting the custom validator over. It should accept:  y, yes,n, no, true, false, on, |off, auto

```yaml
coverage:
  status:
    project:
      default:
        target: auto
```

![Screenshot 2023-08-30 at 4 00 30 PM](https://github.com/codecov/vscode/assets/87824812/5bac261f-faef-4065-83b3-9567a3caefbb)
